// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-dWhBygkTzHGn5w50xMgnPrJC36XtRQ',
    appId: '1:801411016204:web:cfbbbbb3f49db8c3e1b029',
    messagingSenderId: '801411016204',
    projectId: 'login-auth-11',
    authDomain: 'login-auth-11.firebaseapp.com',
    storageBucket: 'login-auth-11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmkSFurUAmpkB0wu2R3DBs7C7dffAqzXs',
    appId: '1:801411016204:android:a9120f7f52e8fcc3e1b029',
    messagingSenderId: '801411016204',
    projectId: 'login-auth-11',
    storageBucket: 'login-auth-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgv3-ca0wF8xdQXSJ7GTZdWHGmecvsChs',
    appId: '1:801411016204:ios:3c1a95ec76342766e1b029',
    messagingSenderId: '801411016204',
    projectId: 'login-auth-11',
    storageBucket: 'login-auth-11.appspot.com',
    iosBundleId: 'com.example.log',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgv3-ca0wF8xdQXSJ7GTZdWHGmecvsChs',
    appId: '1:801411016204:ios:2e00f52d62a65770e1b029',
    messagingSenderId: '801411016204',
    projectId: 'login-auth-11',
    storageBucket: 'login-auth-11.appspot.com',
    iosBundleId: 'com.example.log.RunnerTests',
  );
}
